sudo: required

language: python

services:
    - docker

python:
    - "3.5"

cache:
  directories:
    - plugins/gui/frontend/gosa/build

before_install:
    - sudo killall -9 postgres
    - docker pull cpollmeier/gosa3:devel
    - docker run -d -p 389:389 -p 1883:1883 -p 5432:5432 cpollmeier/gosa3:devel
    - pip install --upgrade pip
    - pip install setproctitle pylint tornado coveralls 'pytest>=2.9' libdbus-1-dev dbus-python
    - export TZ=Europe/Berlin
    - sudo mkdir /tmp/workflows
    - sudo mkdir /etc/gosa
    - sudo cp ./test_conf/config /etc/gosa/

script:
    - cd plugins/gui/frontend/gosa/
    - python2 generate.py -sI build
    - cd ../../../../
    - ./setup.py develop
    - ./setup.py test --addopts="--runslow"

after_success:
    - coveralls