language: python
sudo: false
python:
    - "3.5"
before_install:
    - pip install gunicorn gevent setproctitle
script:
    - ./setup.py develop
    - ./setup.py test
after_success:
    - coveralls --data_file backend/.coverage