sudo: required
dist: trusty
language: python
services:
    - docker
python:
    - "3.5"
cache:
  pip: true
  directories:
    - plugins/gui/frontend/gosa/build
before_install:
    - sudo cp test_conf/org.gosa.conf /etc/dbus-1/system.d/
    - ls -la /etc/dbus-1/system.d/
    - ls -la /etc/init.d/
    - sudo service dbus reload
    - sudo killall -9 postgres # kill systems postgres, as we use the one from docker
    - docker pull cpollmeier/gosa3:devel # download docker container
    - docker run -d -p 389:389 -p 1883:1883 -p 5432:5432 cpollmeier/gosa3:devel # start it
    - pip install --upgrade pip # upgrade pip, we need the latest version
    # some preparations for the tests
    - export TZ=Europe/Berlin
    - sudo mkdir /tmp/workflows
    - sudo mkdir /etc/gosa
    - sudo cp ./test_conf/config /etc/gosa/
install:
    - sudo apt-get install libdbus-1-dev libdbus-glib-1-dev # needed to compile dbus-python
    - pip install setproctitle pylint tornado coveralls 'pytest>=2.9' dbus-python
    #- pip install -e git+https://github.com/bochecha/pygobject.git@pip-install#egg=pygobject
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
script:
    # build the gui, to be able to test it if gets served
    - cd plugins/gui/frontend/gosa/
    - python2 generate.py -sI build
    - cd ../../../../
    # setup GOsa, install deps...
    - ./setup.py develop
    # finally run the tests, with running dbus

    - dbus-launch ./setup.py test --addopts="--runslow"
after_success:
    # send test coverage results to coveralls.io
    - coveralls --merge=coveralls.json